Aeris datepicker
aeris-data/aeris-commons-components-vjs pull request #2
Opened 2019-01-02 09:36 UTC by esteban-em

J'ai intégré (et légèrement modifié) l'exemple de test de Marjorie pour les notifications pour se baser dessus quand on fera les tests pour le datepicker. On pourrait peut-être les faire ensemble si vous voulez.

2019-01-04 16:37 UTC, vlhung requested changes
C'est super :-)
A mon avis, il manque un store pour récupérer la date sélectionnée. Il manque également le index.js pour créer le composant aeris-datepicker lors d'un build.

2019-01-04 16:37 UTC, vlhung commented on src/lib/modules/aeris-datepicker/lang/dates.json
> +    "today": "Aujourdhui",
il manque un ' à aujourd'hui :-)

2019-01-04 16:37 UTC, vlhung commented on src/lib/modules/aeris-datepicker/lang/dates.json
> +{
répertoire assets au lieu de lang? Qu'en pensez vous?

2019-01-07 11:52 UTC, esteban-em commented on src/lib/modules/aeris-datepicker/lang/dates.json
> +{
Pourquoi pas, je ne suis pas contre ^^

2019-01-07 11:53 UTC, esteban-em commented on src/lib/modules/aeris-datepicker/lang/dates.json
> +    "today": "Aujourdhui",
Bien vu! Merci :)

2019-01-07 11:54 UTC, esteban-em commented on src/lib/modules/aeris-datepicker/lang/dates.json
> +{
Par contre je suis pas sûr de comprendre pour le store. On en reparlera quand tu seras là si tu veux.

2019-01-16 14:12 UTC, esteban-em commented
Voilà c'est terminé! 

**Happy testing ;)**

2019-01-21 15:34 UTC, samirboumaza approved these changes
sound good for me

2019-01-21 16:02 UTC, vlhung approved these changes

2019-01-21 16:03 UTC, merged