refactor(icon-button): refactoring
aeris-data/aeris-commons-components-vjs pull request #4
Opened 2019-02-05 12:50 UTC by vlhung

2019-02-06 13:09 UTC, esteban-em requested changes

2019-02-06 13:09 UTC, esteban-em commented on src/lib/modules/ui/components/aeris-ui-icon-button.vue
> +  <div aeris-ui-icon-button>
Pareil que pour le tableau : pourquoi ne pas mettre directement l'élément `<button>` en élément racine du composant ? :smile:

2019-02-07 09:58 UTC, samirboumaza commented on src/lib/modules/ui/components/aeris-ui-icon-button.vue
> +      aria-hidden="true"
pourquoi utiliser des paramètres d'accessibilité?

2019-02-07 10:02 UTC, vlhung commented on src/lib/modules/ui/components/aeris-ui-icon-button.vue
> +  <div aeris-ui-icon-button>
corrigé :-D

2019-02-07 10:03 UTC, vlhung commented on src/lib/modules/ui/components/aeris-ui-icon-button.vue
> +      aria-hidden="true"
bonne question, il y était, du coup je me suis dit pourquoi pas :-)

2019-02-07 14:17 UTC, esteban-em commented on src/lib/modules/ui/components/aeris-ui-icon-button.vue
> +  background: #e2e2e2;
C'est normal les couleurs en dur ?

2019-02-07 14:17 UTC, esteban-em commented on src/lib/modules/ui/components/aeris-ui-icon-button.vue
> +  background: #ddd;
Ici aussi, couleurs en dur.

2019-02-07 16:02 UTC, vlhung commented on src/lib/modules/ui/components/aeris-ui-icon-button.vue
> +  background: #e2e2e2;
j'imagine que la personne qui avait fait ça voulait mettre une couleur par défaut?

2019-02-08 11:04 UTC, merged