Aeris ui input
aeris-data/aeris-commons-components-vjs pull request #5
Opened 2019-02-05 16:11 UTC by vlhung

2019-02-06 13:14 UTC, esteban-em requested changes

2019-02-06 13:14 UTC, esteban-em commented on src/lib/modules/ui/components/aeris-ui-input.vue
> +    updateValue: _.debounce(function(event) {
ES6 : `updateValue: _.debounce(event => this.$emit("input", event.target.value), 100)`

2019-02-06 13:14 UTC, esteban-em commented on src/lib/modules/ui/components/aeris-ui-input.vue
> +<style>
style `scoped`

2019-02-07 09:29 UTC, vlhung commented on src/lib/modules/ui/components/aeris-ui-input.vue
> +<style>
c'est noté :-)

2019-02-07 09:53 UTC, samirboumaza commented on src/lib/modules/ui/components/aeris-ui-input.vue
> +      :placeholder="placeholder"
pourquoi tu veux utiliser un aria-label ? ça s'utilise pas avec un lecteur d’écran?

2019-02-07 10:12 UTC, vlhung commented on src/lib/modules/ui/components/aeris-ui-input.vue
> +      :placeholder="placeholder"
il y était, c'est bien une option d’accessibilité. Je l'ai pas enlevé car je me suis dit pourquoi pas :-P

2019-02-07 10:23 UTC, samirboumaza commented on src/lib/modules/ui/components/aeris-ui-input.vue
> +    updateValue: _.debounce(function(event) {
il faut checker si le champs est vide

2019-02-07 11:10 UTC, vlhung commented on src/lib/modules/ui/components/aeris-ui-input.vue
> +    updateValue: _.debounce(function(event) {
je pense qu'ici on n'en a pas besoin, c'est un un input avec une icône, on retourne la valeur telle qu'elle est. Par contre ce serait le parent de faire le traitement de ces valeurs saisies

2019-02-07 14:22 UTC, esteban-em approved these changes

2019-02-07 16:07 UTC, merged