refactor(commons): add gallery component
aeris-data/aeris-commons-components-vjs pull request #6
Opened 2019-02-07 08:16 UTC by samirboumaza

2019-02-07 11:05 UTC, vlhung requested changes
C'est cool ça marche mais c'est vrai que c'est bizarre avec l'écoute d'event keyup :-P Il manque également index.js et le store à supprimer vu qu'il est vide

2019-02-07 11:05 UTC, vlhung commented on src/lib/modules/aeris-gallery/components/aeris-carrousel-slide.vue
> +      legende: "",
sans e :-)

2019-02-07 11:05 UTC, vlhung commented on src/lib/modules/aeris-gallery/components/aeris-carrousel-slide.vue
> +      default: ""
avec ça c'est mieux () =>{
return {}
} sinon le navigateur râle :-D

2019-02-07 11:05 UTC, vlhung commented on src/lib/modules/aeris-gallery/components/aeris-carrousel-slide.vue
> +<style>
scoped :-)

2019-02-07 11:05 UTC, vlhung commented on src/lib/modules/aeris-gallery/components/aeris-carrousel-slide.vue
> +  min-width: 900px;
doublon :-P

2019-02-07 11:05 UTC, vlhung commented on src/lib/modules/aeris-gallery/components/aeris-gallery.vue
> +    escapeKeyListener: function(evt) {
es6? :-P

2019-02-07 11:05 UTC, vlhung commented on src/lib/modules/aeris-gallery/components/aeris-gallery.vue
> +      default: []
il faudrait une fonction sinon le navigateur râle :-)

2019-02-07 11:05 UTC, vlhung commented on src/lib/modules/aeris-gallery/components/aeris-carrousel-slide.vue
> +    img: {
image? :-)

2019-02-07 11:06 UTC, vlhung commented
Il y a également 3 console.log à enlever :-P

2019-02-07 14:09 UTC, esteban-em requested changes
Bon boulot Samir ;)

Par contre, il me semble que tu n'as pas géré le cas d'une légende très longue avec un `overflow: auto`. Il faut donner à l'élément une hauteur fixe ou max pour que ça marche (au cas où). 
Et tu peux aussi ajouter une `margin-top: 10px` à la légende à mon avis :)

Après ça n'a pas l'air très responsive chez moi, mais on n'a pas de specs, donc c'est pas de ta faute :stuck_out_tongue_closed_eyes: 

**Edit :** ça a l'air d'être responsive sur Chrome. Je t'accorde le bénéfice du doute :wink:

2019-02-07 14:09 UTC, esteban-em commented on src/lib/modules/aeris-gallery/components/aeris-carrousel-slide.vue
>    min-width: 900px;
`min-width: 900px;` deux fois ici ^^

2019-02-07 14:09 UTC, esteban-em commented on src/lib/modules/aeris-gallery/components/aeris-gallery.vue
> +      default: []
`default: () => []`

2019-02-07 14:09 UTC, esteban-em commented on src/lib/modules/aeris-gallery/components/aeris-gallery.vue
> +      console.log("index", index);
`console.log` à enlever

2019-02-07 14:09 UTC, esteban-em commented on src/lib/modules/aeris-gallery/components/aeris-gallery.vue
>      escapeKeyListener: function(evt) {
ES6 : `escapeListener(evt) {...}`

2019-02-08 07:56 UTC, samirboumaza commented on src/lib/modules/aeris-gallery/components/aeris-gallery.vue
> +    escapeKeyListener: function(evt) {
omg le vieux copié/collé :p

2019-02-08 11:40 UTC, merged